name: Add maintainer checklist
description: Reminder to check list of steps when modifying team
body:
  - type: markdown
    attributes:
      value: >-
        If you are adding or removing someone from a team, please check that the list of items on the
        [Adding New Role Members page](https://github.com/astropy/astropy-project/blob/main/policies/adding-new-role-members.md)
        has been completed. In particular, the following.
  - type: checkboxes
    id: add-maintainer-checklist
    attributes:
      label: Reminder to check list of steps when modifying team
      description:
      options:
        - label: PR to the [Team page](https://github.com/astropy/astropy.github.com/blob/main/roles.json)
        - label: privileges and/or permissions updated
        - label: (if adding a new member) email to the community
        - label: update membership of the astropy-core-maintainers mailing list
