name: Request funding (travel)
description: Submit a public request for travel funding from Astropy
title: "Request for Travel Funding"
labels: "finance :moneybag:,funding :pray:,travel ✈️"
body:
  - type: markdown
    attributes:
      value: >-
        Thanks for taking the time to fill out this travel request!
        Please read [Guidelines for Requesting Funding](https://github.com/astropy/astropy-project/blob/main/finance/process/request-funding.md)
        carefully before submitting this request.
        This is a public repository, please scrub out sensitive information.
  - type: textarea
    attributes:
      label: Full name
      description: Who is traveling
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Purpose of the travel and how it benefits Astropy.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Total request
      description: Total amount requested and currency.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Itemized budget
      description: Total amount broken down into items.
      placeholder: |
        Lodging: $1000 ($200/night for 5 nights)
        Flights: ...
        Per diem: ...
        etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Advance needed
      description: Whether you need any advance and if so, how much
