name: Request funding (other)
description: Submit a public request for other funding from Astropy
title: "Other Request for Funding"
labels: "finance :moneybag:,funding :pray:"
body:
  - type: markdown
    attributes:
      value: >-
        Thanks for taking the time to fill out this other funding request!
        Please read [Guidelines for Requesting Funding](https://github.com/astropy/astropy-project/blob/main/finance/process/request-funding.md)
        carefully before submitting this request.
        This is a public repository, please scrub out sensitive information.
  - type: textarea
    attributes:
      label: Full name
      description: Name of person requesting funding
    validations:
      required: true
  - type: textarea
    attributes:
      label: Purpose
      description: Explanation of the funding being requested
    validations:
      required: true
  - type: textarea
    attributes:
      label: Budget
      description: Amount requested and currency
    validations:
      required: true
